name: 'Swagger Parser'
description: 'Parses, validates, dereferences an OpenAPI definition'
inputs:
  inputSpec:
    description: 'path to OpenAPI definition file'
    required: true
  options:
    description: 'parser options'
    required: false
  serializationType:
    description: 'result file serialization type'
    required: false
  logsPath:
    description: 'path to validation result file'
    required: false
  parserSpecPath:
    description: 'output path of the serialized parsed definition'
    required: false
  parserVersion:
    description: 'parser version'
    required: false
runs:
  using: "composite"
  steps:
    - id: java-version
      run: java -version 2>&1 | fgrep -i version | cut -d'"' -f2 | sed -e 's/^1\./1\%/' -e 's/\..*//' -e 's/%/./'
      shell: bash
    - name: Build Java
      if: steps.java-version == null || steps.java-version < 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Download JAR
      run: curl -L 'https://oss.sonatype.org/service/local/repositories/snapshots/content/io/swagger/parser/v3/swagger-parser-cli/2.1.3-SNAPSHOT/swagger-parser-cli-2.1.3-20220927.002610-8.jar' -o swagger-parser-cli.jar
      shell: bash
    - id: execute
      name: Execute Jar
      run: java -jar swagger-parser-cli.jar -i /home/runner/work/${{ inputs.inputSpec }} ${{ inputs.options }} ${{ inputs.serializationType }} -o /home/runner/work/${{ inputs.parserSpecPath }} -l /home/runner/work/${{ inputs.logsPath }}
      shell: bash